# Generated by Django 4.0.5 on 2022-06-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
