# Generated by Django 4.0.5 on 2022-06-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
