# Generated by Django 4.0.5 on 2022-06-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_remove_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
