# Generated by Django 4.0.5 on 2022-06-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
    ]
