# Generated by Django 4.0.5 on 2022-06-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_remove_cart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
